### ISSUE TITLE
Comments from 茱滴 (Alibaba)

### ISSUE THREAD

**Issue by rigow** [w3c/websec#10]
High level: the Crypto API、Web Storage API、Web Worker etc  in this charter
have already been defined in the W3C, so it is not clear the scope and the
definition of the hardware aspect. You may need to clarify clearly in the
charter. 

Details: 
1.       The mission of the  https://w3c.github.io/websec/Overview.html
   Hardware Security Working Group, part of the
   https://w3c.github.io/Security/Activity.html Security Activity, is to
   define a set of Hardware-Based Web Security standard services providing Web
   Applications usage of secure services enabled by hardware modules

Suggestion: mission should not define the standard service, it should be
standards, so it should remove the “services”word.

2、2.1  Deliverable，
-       Secure Hardware Crypto Key Management: Importing, creating, deleting
  keys for a particular origin. Working Group would define trust/permission
  model for use of this API.

Question and which needs clarification: What do you mean by this API here by
red color highlighted? 

3、Secure Hardware IO，从后面的描述里面，主要是关于User Interface的，建议把
IO改成User Interface；IO一般指的输入输出；

```
  Secure Hardware IO：Means to ask for and obtain user input that is
```

protected against compromised operating system or UA/Browser depending on
the level provided. This could return a digitally signed (by the hardware
component) response from the user.

Suggestion: pls change the IO to user interface, because common sense IO
means input and output.

4、2.1 Secure Worker: API to execute JavaScript or WebAssembly code in a
Secure Hardware Component (allowing, but not necessarily requiring both).  

Question: What is the difference between the secure worker and web worker?
W3c has already defined “web worker”/

5、2.1 Identity semantics: Means to extract identity information from a
secure hardware under control of the user, including the choice or creation
of the subsequent data format made available via the API.

What is the difference between this and ietf stuff?

**Comment by vgalindo** [comment]
initial text : The mission of the https://w3c.github.io/websec/Overview.html Hardware Security Working Group, part of the https://w3c.github.io/Security/Activity.html Security Activity, is to define a set of Hardware-Based Web Security standard services providing Web Applications usage of secure services enabled by hardware modules
--> suggestion 
The mission of the https://w3c.github.io/websec/Overview.html Hardware Security Working Group, part of the https://w3c.github.io/Security/Activity.html Security Activity, is to define a set of Hardware-Based Web Security standard APIs providing Web Applications access to secure services enabled by hardware modules

**Comment by vgalindo** [comment]
initial text : Secure Hardware Crypto Key Management: Importing, creating, deleting keys for a particular origin. Working Group would define trust/permission model for use of this API.
--> suggestion
Secure Hardware Crypto Key Management: Importing, creating, deleting keys for a particular origin. Working Group would define trust/permission model for use of cryptographic functions

**Comment by vgalindo** [comment]
initial text : Secure Hardware IO: Means to ask for and obtain user input that is protected against compromised operating system or UA/Browser depending on the level provided. This could return a digitally signed (by the hardware component) response from the user. 
--> suggestion
Secure Hardware user interaction: Means to ask for and obtain user input that is protected against compromised operating system or UA/Browser depending on the level provided. This could return a digitally signed (by the hardware component) response from the user.

**Comment by vgalindo** [comment]
On comment about secure worker
Secure worker will be a web-worker-like execution thread, which operations will be executed in a secure way, no further clarification needed in the charter, I guess.

**Comment by vgalindo** [comment]
On comment about identity 
That identity semantic is about using national identity scheme, the way it is phrased here is very abstract, thus it may seem redundant with other work happening in other identity related items. We need to make that sentence linked with the gov use case. 
--> suggestion 
Identity semantics: Means to extract citizen identity information from a
secure hardware under control of the user. 

_Rigo: I don't think that works as the national identity scheme is not precluding a consumer loyalty program to also use certain type of smartcards, so I don't think tying to GovIDs helps._

**Comment by rigow** [comment]
All suggested changes except for the _Identity semantics_ edited and pushed into repository

**Comment by wcarr** [comment]
With a lot of different issues, it can be better to raise separate issues on the separate topics.  That way people with the same issue can discuss it there and it's clearer which parts have already been addressed.  I suggest raising new separate issues for anything not still addressed.

**Comment by wayneca** [comment]
Secure Worker comment

> 4、2.1 Secure Worker: API to execute JavaScript or WebAssembly code in a
> Secure Hardware Component (allowing, but not necessarily requiring both).
> 
> Question: What is the difference between the secure worker and web worker?
> W3c has already defined “web worker”

A Web Worker executes in the Web Browser.  A compromised Browser or OS means execution of the Worker could be tampered with.  A Secure Worker would execute in a hardware secure context where that can't happen.  Web Workers have a set of APIs available to them.  Other types of Workers can have different APIs.   Service Workers is an example of that.   Secure Workers would have a set of APIs available, defined by the WG, that likely would include the other hardware secure APIs defined by the group.  They'll also have some way of indicating something like the level of security provided and possibly who vouches for it (through the Discover & Attestation scope item in the Charter).

But, conceptually it is similar to Web Workers.  Code is executed (but in a secure environment) and communicates through messaging back to the Web page code.

I don't think the charter text needs to changed.

**Comment by wayneca** [comment]
on the general comment at the top

> High level: the Crypto API、Web Storage API、Web Worker etc in this charter
> have already been defined in the W3C, so it is not clear the scope and the
> definition of the hardware aspect. You may need to clarify clearly in the
> charter.

The W3C Web Cryptography WG will complete its spec and then will end its work.  This proposed WG is picking maintenance of that up.

Storage here will be in a secure hardware component where it can't be tampered with.  The other APIs for storage could be implemented that way.  But, there's no guarantee they are.  The WG will decide on the API, but it could be very similar to an existing API with a means of requesting secure storage and a way to confirm its secure (the first restricted scope item).  e.g. it could be an extension of an existing API. The WG will figure that out.

Web Worker was discussed in the previous comment.

Most of these are a way to use secure hardware to do a common thing and to be sure you are doing that.  That makes it much easier to handle the long list of deliverables because everything doesn't have to be reinvented.  I don't think anything needs to change in the charter for this part.

**Comment by wayneca** [comment]
Is everything taken care of except identity?  If so, I suggest closing this Issue and opening another one on that, so people can see the Issue is about that and comment on it.

> 5、2.1 Identity semantics: Means to extract identity information from a
> secure hardware under control of the user, including the choice or creation
> of the subsequent data format made available via the API.
> 
> What is the difference between this and ietf stuff?

**Comment by vgalindo** [comment]
@rigow @wcarr I guess issue part related to identity semantic can be closed, thanks Wayne.

**Comment by vgalindo** [comment]
@wcarr On the storage aspects, I believe there is no need to define a 'storage API' in the hardware security working. there will be some services to manage keys, to manage identities, but not really a service allowing to store any type of data. I think this is where the confusion is coming... What do you think ?

**Comment by kepengli** [comment]
Do we have a related draft spec for the proposed work?

I heard that for the new proposed work, it is recommended to have a draft spec to help people to understand the proposal, and understand the potential outcome.

**Comment by cyberphone** [comment]
Opened a separate HW-secured IO issue: https://github.com/w3c/websec/issues/19

**Comment by cyberphone** [comment]
Opened a separate HW WebCrypto issue: https://github.com/w3c/websec/issues/20

**Comment by rigow** [comment]
We don't have a Specification of the proposed work and this is not necessary according to the process in order to start work. Having a Draft Specification before having a charter may be useful in some context and less useful in some other context. 

I think all comments from Alibaba were addressed, so closing the issue as suggested by Wayne
