### ISSUE TITLE
3.1 Sweden's eID

### ISSUE THREAD

**Issue by cyberphone** [w3c/websec#105]
Although there is a Tax agency and Telia eID card, practically everybody uses an entirely different solution called Mobile BankID which also is used for mobile banking.  Recently the system has been upgraded for authorizing P2P payments.  Note: all these services are based on the same credential.

It may in this context be interesting knowing that after the browser vendors announced that they would remove support for plugins, signatures are nowadays NOT performed using browsers, but in stand-alone native applications which gives a poor user experience.

**Comment by sbahloul** [comment]
If I understand you, the mobile app is not relying on any secure device, so this is out of scope of the CG

**Comment by cyberphone** [comment]
The reason why Mobile BankID does not rely on security hardware is not because the banks don't want such, it is rather the absence of a credentialing standard supporting TEEs that made them default to "App" security.  I'm unable to tell if the CG intends supporting "platform" level key provisioning or not.  AFAIK, FIDO tokens support both the Web and "Apps".

**Comment by vgalindo** [comment]
@cyberphone @sbahloul guys, I dont get that conversation. Is there any suggested change to the report ?

**Comment by sbahloul** [comment]
Not from my point of vue: we are working at W3C to update web interfaces, not mobile APIs.
