### ISSUE TITLE
[hbss] Editorial remark - Some typos

### ISSUE THREAD

**Issue by brunojav** [w3c/websec#107]
Some small typos listed below : 
typos :
Line 86 : <li>[...] the genuine user is authorized to used the keys. [...]
    to : <li>[...] the genuine user is authorized to use the keys. [...]

Line 95 : <p> [...] Secure Services Community Group as being as key to enabling a strong security and identity ecosystem.</p>
    to : <p> [...] Secure Services Community Group as being as key to enable a strong security and identity ecosystem.</p>

Line 102 : <p>"In this document, we assume that: 
    to (no unexpected double quote) <p>In this document, we assume that:

Line 118 : add a colon at the end of the line

Line 126 : [..]  One should read those use cases as attractive for in web application scenario.
    >> is it a typo or an expression ("for in web scenario")

Line 153 : <p>[...] In some conditions, usually defined by the bank, some extra security are requested to the consumer to finalize transactions. [...]</p>
    to : <p>[...] In some conditions, usually defined by the bank, some extra security is requested to the consumer to finalize transactions. [...]</p>

Line 364 :  Resolve <var>promise</var> with <var>signature</var> and, if applicable, <var>key</var>the public part of key used to sign.
    to :  Resolve <var>promise</var> with <var>signature</var> and, if applicable, <var>key</var> the public part of key used to sign.

Line 438 : Resolve <var>promise</var> with <var>signature-nrmessage</var> and, if applicable <var>key</var>the public part of key used to sign.
    to : Resolve <var>promise</var> with <var>signature-nrmessage</var> and, if applicable <var>key</var> the public part of key used to sign.

Line 544  : <p>Window interface is enhanced to expose a the hardware secure device management service.</p>
    to : <p>Window interface is enhanced to expose hardware secure device management service.</p>

Line 588 : <p>The attribute hardwaresecuredevices represents the list of hardware secure devices presents and [...]
    to : <p>The attribute hardwaresecuredevices represents the list of hardware secure devices present and [...]    

Line 594 : UA MAY defines other classes extending the HardwareSecureDevice one representing different type of hardware secure device with specific implementation. One implementation COULD be using PKCS#11 as transport layer to communicate with a compatible hardware securedevices</p>
    to : UA MAY define other classes extending the HardwareSecureDevice one representing different types of hardware secure device with specific implementation. One implementation COULD be using PKCS#11 as transport layer to communicate with a compatible hardware secure device</p>

Line 767 : But there is no capability to add middleware. It is up the OS manufacturer to provide support for the
    to : But there is no capability to add middleware. It is up to the OS manufacturer to provide support for the

**Comment by sbahloul** [comment]
Hi Bruno

I didn't catch the following point: 

Line 767 : But there is no capability to add middleware. It is up the OS manufacturer to provide support for the
to : But there is no capability to add middleware. It is up to the OS manufacturer to provide support for the
