### ISSUE TITLE
[hbss] Editorial remark - In case of printing document

### ISSUE THREAD

**Issue by brunojav** [w3c/websec#108]
In order to have a better reading I'd propose : 

Line 9 from <body> to <body style="text-align: justify;">
Line 107 from : embed the sentence in &lt;p&gt;&lt;/p&gt; to avoid this sentence stuck to next paragraph. (seems &lt;p&gt; and &lt;ul&gt; are not compatible)

**Comment by sbahloul** [comment]
Fixed in all the document
