### ISSUE TITLE
4.2.2 Permission

### ISSUE THREAD

**Issue by cyberphone** [w3c/websec#110]
> UA MUST not start to exchange with an Hardware Secure Device without the express permission of the user. UA MUST acquire permission through a user interface, unless they have prearranged trust relationships with users

Converted to practice: http://webpki.org/papers/permissions.pdf

**Comment by sbahloul** [comment]
And so ?

**Comment by cyberphone** [comment]
Well, it is (for me at least), not evident what kind of permission requests you are planning and their interpretability for non-expert users.

**Comment by vgalindo** [comment]
@cyberphone This IG does not intend to solve all the problem, the permission aspects will be implementation specific. 
@sbahloul I suggest we close this issue

**Comment by cyberphone** [comment]
@sbahloul @vgalindo HTTPS client-certificate authentication is AFAIK currently the only browser-supported subsystem/API that is used with secure hardware such as smart cards.  It does not require user permissions of the kind mentioned in the report.

Apple's recently previewed Apple Pay for the Web is built around their "Security Enclave" HW, and it doesn't need such permissions either.

What I'm trying to say here is that the security model featured in the proposed API would benefit from a deeper discussion.
