### ISSUE TITLE
Transport Layer (by KM)

### ISSUE THREAD

**Issue by vgalindo** [w3c/websec#114]
Section 3.1: National Electronic Identity for Accessing Public Services
Text: The native environment of the citizen device, or of the public service office, is able to access to the hardware token, thanks to a transport layer (USB, ISO 7816 / 14443, Bluetooth Low Energy ...).

Question: Who defines the transport layer?

**Comment by vgalindo** [comment]
My understanding is that th transport layer os out of scope fo this CG, as it will be up to the browser the bridge the actual physical connection with the hardware based token.

**Comment by sbahloul** [comment]
I have also the same understanding.

**Comment by vgalindo** [comment]
@sbahloul  I suggest we close this issue.
