### ISSUE TITLE
Permission and MUST (by KM)

### ISSUE THREAD

**Issue by vgalindo** [w3c/websec#119]
Section 4.2.2: Permission
Text: UA MUST not start to exchange with an Hardware Secure Device without the express permission of the user
Question: Should this be a “MUST” requirement.  Isn’t this dependent on the UVMMode?

**Comment by sbahloul** [comment]
The UVMMode is a switch when the end-user has already accepted to allow the relying party to use the Hardware Secure Device. If there were no end-user authorization, it would allow a third party to track the end-user by generating and using keys which would not be acceptable from a privacy perspective

**Comment by sbahloul** [comment]
@Ketan2016

**Comment by Ketan2016** [comment]
Ok, I understand.
