### ISSUE TITLE
Web payments access Restricted Scope Item is too vague or doesn't belong in that section

### ISSUE THREAD

**Issue by wayneca** [w3c/websec#14]
> Web payments access: Cooperate with the Web payments WG to allow 
> access to payment related hardware via the hardware APIs developed 
> within the HASEC Group.

The point of the Restricted Scope Items list in the Charter is to be very specific about the technical nature of the Working Group Recommendation deliverables (where "Recommendation" is W3C's term for what other standards organizations call "Specification").  That is so prospective participants can estimate the type of patents that they may be required to license by joining the group (according to the Patent Policy which applies to W3C Recommendations), without having to list exhaustively every actual specification the group is permitted to produce.    That all depends on the Restricted Scope Items being very clear and very narrow, with no wild cards about being able to do anything at all useful to solve some wide problem (like anything needed for Web Payments, or anything needed for Web Security).

It the "Web payments access" Restricted Scope Item in the proposed Charter is meant to be a new area in the Restricted Scope Item, then it is too vague.  It would be a wild card permission to do anything the Web Payments WG wanted or that the Hardware Security WG thought they should have. 
This item as written seems looks to be: "and anything else the Web Payments Working Group wants or that the Hardware Security Working thinks may be useful in any way for use in payments".  That would be inappropriate.  With a Restricted Scope Item like that, none of the other Restricted Scope Items would be needed to be listed because any of those specs could be useful in some way for payments.

This item may be intended to mean:  "The Hardware Security Working Group is expected to have a close relationship with the Web Payments Working Group.  The Hardware Security group would welcome use cases from the Web Payments Working Group related either to current specifications in scope under this Charter or for consideration in developing the scope for specifications in future Charters.  The Hardware Security Working Group may also produce non-specification documents related to the Web Payments Working Group for things like use cases for that group's specifications (where the use cases may benefit from Hardware Security WG specifications) or best practices on how to use Hardware Security WG specifications in payments."   

If that is the intent, then the paragraph above should be the second paragraph of the Scope section of this Charter, not an item in the Restricted Scope section.  It would NOT be about extending the Restricted Scope items.  It would be about non-specification documents.

**Comment by vgalindo** [comment]
@wcarr :+1: 
Lets put that in a separate section, scope section will be okay. I expect only to have 'discussion document' on that topic and a beginning of architecture after 18 months, as this work will strongly depends on Web Payment progress

**Comment by vgalindo** [comment]
I suggest we create a 2.3 section 
2.3 Other Deliverables
The Working Group will work on web payments access thanks to a cooperation with the Web payments WG. The expected non normative deliverables are use case and an architecture document, focusing on payment integration in the web payment API designed when payment means relies on hardware.
@rigow, @wcarr  what do you think ?

**Comment by wayneca** [comment]
yes, looks good.  this can close with that.

**Comment by rigow** [comment]
Created PR #32 and will merge soon
