### ISSUE TITLE
Scope privacy and fingerprinting paragraph needs rewording

### ISSUE THREAD

**Issue by wayneca** [w3c/websec#15]
Current text in proposed Charter:

> Because web app using services providing some security sensitive functions 
> may be sensitive to the users, this WG will take special care to make sure 
> that the deliverables do not break user privacy and potential anonymity. 
> As such, deliverables will take special care of fingerprinting and tracking threats. 
> In addition, some mechanisms will be associated to make sure security functions 
> will be used under the user control.

Suggested alternative wording: 

> Specifications like those to be produced by this group could impact
> user privacy and potential anonymity.  Special care will be taken to avoid
> introducing fingerprinting and tracking threats in deliverables from this group. 
> One mechanism to alleviate these potential problems is to place permission
> to use some functions under the user's control in a way in which the user
> understands the privacy implications.  The group will seek review
> from the Privacy Interest Group.

**Comment by vgalindo** [comment]
@wcarr :+1: with this suggestion.

**Comment by rigow** [comment]
Committed by https://github.com/w3c/websec/commit/b51f544572432bedcf569dbb7d411fa3f175f58a
