### ISSUE TITLE
Identity semantics comments in its own Issue

### ISSUE THREAD

**Issue by wayneca** [w3c/websec#16]
Identity semantics comments were in two Issues that covered multiple topics.  Copying those to an Issue just on that since it seems an issue not resolved yet. (doing this so the other issues could be closed if the rest of them were settled and also so that people with comments on this topic would see it had been raised and could comment on it)

Question on this in #10 

> 2.1 Identity semantics: Means to extract identity information from a
> secure hardware under control of the user, including the choice or creation
> of the subsequent data format made available via the API.
> 
> What is the difference between this and ietf stuff?

[Response in that issue](https://github.com/w3c/websec/issues/10#issuecomment-165434627)

> On comment about identity 
> That identity semantic is about using national identity scheme, the way it is phrased here is very >abstract, thus it may seem redundant with other work happening in other identity related items. We >need to make that sentence linked with the gov use case. 
> -> suggestion 
> Identity semantics: Means to extract citizen identity information from a
> secure hardware under control of the user.
> 
> Rigo: I don't think that works as the national identity scheme is not precluding a consumer loyalty >program to also use certain type of smartcards, so I don't think tying to GovIDs helps.

Question on this in #9 

> 2.1. should respectively not only cover 'Identity semantics' (which I find kind of unwieldy and unclear)

That went on to discuss other topics and the side comment hasn't been addressed.

**Comment by vgalindo** [comment]
@wcarr thanks for helping the discussion being focused
Taking into account the broad vision suggested by @rigow I am suggesting the following wording : 

including in the charter, for the identity API : "Means to extract identity information from a secure hardware under control of the user. This API will define a set of services, abstract enough to be usable with citizen identity, loyal identity or any service offering identity scheme based on hardware security token."

Thought ?

**Comment by cyberphone** [comment]
Since a citizen identity can't be bound to an origin it is a non-starter since the browser vendors have clearly expressed that they won't support such a thing as an _integral part of the browser_.  In fact, they are actively trying to _remove_ the limited support that exists today.

**Comment by kepengli** [comment]
In IETF, there is a SCIM (System for Cross-domain Identity Management ) work: https://datatracker.ietf.org/wg/scim/charter/. The work is almost done. The System for Cross-domain Identity Management (SCIM) working group will standardize methods for creating, reading, searching, modifying, and deleting user identities and identity-related objects across administrative domains, with the goal of simplifying common tasks related to user identity management in services and applications.

It defines both the identity semantics and APIs to CRUD identities. So I want to know the difference with that work.

**Comment by cyberphone** [comment]
@kepengli As far as I understand SCIM is about things happening on the server/cloud level rather than in the UA or local security hardware.  SCIM may drive use-cases involving the UA but for provisioning an identity via the UA into a end-user device there are no standards at all.  FWIW, the latter is something I have worked with in various contexts for over a decade:
https://cyberphone.github.io/openkeystore/resources/docs/keygen2.html

**Comment by rigow** [comment]
Of course SCIM and eIDAS haven't coordinated at all. But SCIM does not need hardware components. A HASEC API and service should be able to cater to SCIM and eIDAS alike, but it is not meant to use only one or the other. As this is not affecting the charter, I'm closing the issue.

**Comment by cyberphone** [comment]
@rigow It is possible that this issue has multiple interpretations.  Provisioning of identities in HW-protected containers is a complex topic that's currently missing.

**Comment by rigow** [comment]
@cyberphone  I think it is not missing, but hidden in the eIDAS use case and the "services" definition. If you're ok with this, I keep the issue closed, if not let us reopen the issue
