### ISSUE TITLE
HaSec: Making phone tokens "phishsafe"

### ISSUE THREAD

**Issue by cyberphone** [w3c/websec#17]
Since phone tokens have become the most popular 2FA-method for authenticating to on-line services, it is somewhat disappointing that most of these systems are fully "phishable".

Is there a Hardware solution to this problem you may wonder? Yes, using NFC.

**Comment by vgalindo** [comment]
@cyberphone I think that this is not an issue that WG will address, as the authentication aspects are treated in the Web Authentication WG (under W3C members review)

--> I suggest we close that issue

**Comment by cyberphone** [comment]
@vgalindo I guess your refer to: http://w3c.github.io/websec/web-authentication-charter

If this represents FIDO alliance's view of phone tokens (?), it is limited to U2F and also _fundamentally departs_ from how phone tokens actually are used since at least 15 years back.

Naturally you should close the issue if you feel that this work should be carried out somewhere else.

**Comment by vgalindo** [comment]
@cyberphone I am refering to that WG, I believe this is where that discussion should happen. 

--> I suggest we close the issue.

**Comment by cyberphone** [comment]
@vgalindo This discussion won't happen in that WG since the sole purpose of the Web Authentication WG (_given the current charter NB_), is rewriting FIDO documents (_without changing anything since that would break implementations_) into the W3C format and then calling them W3C standards which is of no interest to anybody but the W3C.

Closing the issue as requested.
