### ISSUE TITLE
Clarify licensing in charter

### ISSUE THREAD

**Issue by rigow** [w3c/websec#18]
Suggested from Wayne. Be very clear which license the WG should use, the forking or the non-forking option

**Comment by rigow** [comment]
I had an offline discussion with Wayne and the new document license seems fine

**Comment by wayneca** [comment]
I'm not sure which one that means.  Shouldn't there be a licensing section like in the [Web Authentication WG Charter](http://w3c.github.io/websec/web-authentication-charter#licensing) to say which of the two Document licenses?

[W3C Software and Document License](http://www.w3.org/Consortium/Legal/2015/copyright-software-and-document)

[W3C Document License](http://www.w3.org/Consortium/Legal/2015/doc-license)
