### ISSUE TITLE
HaSec: Hardware protected user I/O

### ISSUE THREAD

**Issue by cyberphone** [w3c/websec#19]
This has been proposed by parties like GlobalPlatform.

What's missing here is a discussion what is actually achievable and approximately how.  There appears to be a number of problems with this concept such as:
- How are users supposed to recognize the difference between a trusted and (potentially) non-trusted display?
- How is a trusted display programmed?  Simply downloading HTML doesn't seem to be enough.
- Doesn't this dramatically complicate hardware unless the graphic system is in the same SoC?

If the primary use-case is specifying PIN-codes, there's no absolute need for trusted input.  Schemes like https://cyberphone.github.io/openkeystore/resources/docs/web2native-bridge.pdf#page=4 achieve similar functionality by restricting key-operations including PINs to locally trusted applications.  A "spoofed" display may indeed be used to steal a PIN but this won't buy the attacker much since the PIN cannot be used except through physical access to the device which is a quite different matter, presumably way out of scope for this work-group.

**Comment by vgalindo** [comment]
@cyberphone that discussion will happen once the WG will be open. Lets keep your contribution for achive. 
--> I suggest we close this issue (ping @rigow )

**Comment by cyberphone** [comment]
@vgalindo This is an input specification.  I hope that the WG won't open without having such on the table.  Fee free do whatever you want with this :-)

**Comment by rigow** [comment]
@cyberphone I count on you to re-raise the issue once the WG is running. Closing for the moment
