### ISSUE TITLE
Contribution mechanism?

### ISSUE THREAD

**Issue by kpfleming** [w3c/websec#2]
This repository contains only HTML versions of the charters, but I assume that's not how they were authored. I have some changes to propose, and it would be easiest to send a pull request, but I can't send it against the source files because they aren't here :-)

How would you like to receive contributions?

**Comment by wseltzer** [comment]
They were authored in HTML, so you have the source. Feel free to send PRs or put the text into issues.

**Comment by kpfleming** [comment]
OK, thanks. Is there any plan to update the web-authentication charter to use the fancy template that the ha-sec charter uses?

**Comment by wseltzer** [comment]
The styling could be a mixed-content issue that's resolved when w3.org goes https
