### ISSUE TITLE
HaSec: HW-protected WebCrypto Keys

### ISSUE THREAD

**Issue by cyberphone** [w3c/websec#20]
This can be achieved by creating a single new method which approximately would work as the registration in U2F.  That is, attestation would be a part of the result.

There have been suggestions adding an attribute to keys saying if they are HW-protected or not.  This is not necessary since attestation during key generation/registration provides such information and in a SOP-restricted concept like WebCrypto it is up to the domain keeping this information somewhere if needed.  In PKI it is usually an implicit or explicit policy defined by the issuer as a comparison.

Note that registration a la U2F does NOT require keys to be HW-protected, it only attests the characteristics of the key-container.  This is a fully universal solution (unlike a possible HW-protected attribute which doesn't come with a quality assurance).

**Comment by vgalindo** [comment]
@cyberphone what is exactly your issue ? I dont see anything to solve here that will impact the charter. 
--> I suggest we close the issue (ping @rigow)

**Comment by cyberphone** [comment]
@vgalindo It is simply a clean-up of one of the multiple issues mentioned by Alibaba.  It doesn't impact the charter more (or less) than the original issues so feel free do whatever you want with it :-)

**Comment by rigow** [comment]
Ok, so closing this issue. As it does not affect the charter but is one of the possible choices within the charter I suggest further discussion within the WG, not over the charter..
