### ISSUE TITLE
Duplicate "deliverables"?

### ISSUE THREAD

**Issue by wseltzer** [w3c/websec#26]
Since the group's potential deliverables are described in Section 2.1, it's not clear what function Section 3 serves. This was confusing to a reader.

**Comment by wayneca** [comment]
There is always a scope section and a deliverables section in W3C WG Charters.  Each of those is a requirement in the [W3C Process Document](https://www.w3.org/2015/Process-20150901/#WGCharter)

Between the two of them it has to be clear what specs the WG is permitted to produce with enough detail that those considering joining can evaluate what types of patent licensing may be required. 

In many charters the deliverables section describes the exhaustive list of specs that will be produced and they have to recharter to add another deliverable.  In this proposed Charter, it hasn't been decided which of the possible specs will be produced by the group.  

So the scope is very carefully described in section 2 (so people can consider possible licensing obligations).  And in the deliverables section 3, it says that deliverables that are chosen later by the WG have to match the restricted scope items in the scope and have to be listed in a set place -- as opposed to exhaustively listing all the specs that will be produced in the Charter.

So both sections are needed.

**Comment by wseltzer** [comment]
Then the connection between the two needs to be made clearer, such as "Deliverables will be identified from among those listed in 2.1" -- and the group doesn't have to recharter to select among those, I hope!

**Comment by rigow** [comment]
PR #28 from @wseltzer now merged into gh-pages

**Comment by wseltzer** [comment]
My PR was on a different issue. This language is still unclear. I added PR 33 https://github.com/w3c/websec/pull/33

**Comment by rigow** [comment]
this was merged yesterday
