### ISSUE TITLE
Extraneous sentence in success criteria (2.4)?  

### ISSUE THREAD

**Issue by wseltzer** [w3c/websec#27]
The first sentence of 2.4, " If the Working Group successfully identifies at least one candidate protocol or API in this manner, it may suggest a charter for further work in this area." looks out of place. (in what manner?) Should that sentence be deleted?

**Comment by wayneca** [comment]
Left over from other Charter that was used as a template?  Definitely doesn't belong here.

**Comment by drogersuk** [comment]
Agree, we should get rid of that.

**Comment by wseltzer** [comment]
Proposed PR 28:  https://github.com/w3c/websec/pull/28

**Comment by rigow** [comment]
yes and yes, merged PR #28
