### ISSUE TITLE
[hasec charter] Success Criteria should include a publishing deliverable

### ISSUE THREAD

**Issue by swickr** [w3c/websec#41]
Section 2.4 Success Criteria places a lot of emphasis on discussion and little on producing documents.

At a minimum, the second bullet could change from "elaboration of a NOTE" to "publishing a WG NOTE".  A further improvement would be to add bullet(s) saying that the Group will have selected at least one (and preferably more) of the Restricted Scope items and published a Recommendation-track specification, since that is explicitly a Goal per section 1.

**Comment by vgalindo** [comment]
@rigo 
I agree, lets implement that.
Proposed resolution : 
One or several recommendations will be developed from the use case and requirements, after priority management by the WG.

**Comment by rigow** [comment]
done with PR #56
