### ISSUE TITLE
[hasec charter] Clarify "specific deliverables"

### ISSUE THREAD

**Issue by swickr** [w3c/websec#42]
Section 3.1 Recommendation-Track Deliverables speaks of rechartering in its penultimate sentence.  Clarify whether the intention is to allow Recommendation-Track deliverables that address a Restricted Scope item to be produced under this charter or not.  Is the intent that rechartering is [only] necessary to add Restricted Scope items beyond those currently listed?

The final sentence of 3.1 contributes to this confusion.  If the intent is only to say that the charter does not state which of the Restricted Scope items the Group _should_ work on, that is obvious by inspection and I recommend dropping the sentence.  If the intent is to say that the Group _must_ recharter once it has identified a Recommendation-track specification within the Restricted Scope items that would be in conflict with the first goal stated in section 1.

**Comment by wayneca** [comment]
@swickr I proposed wording #46 to specifically say the group is permitted to produce specs under the Restricted Scope Items.  Those are listed outside the charter in a place given in the Charter.

The part about rechartering to add a REC was meant to say that the WG can also specifically add a REC track deliverable to the charter if they want to.  But, they don't have to if already permitted to create it under the Restricted Scope items.  When this group recharters and has REC track specs already published that it is working on, I'd think the next Charter would list those.

The purpose of Restricted Scope Items is to enable carefully describing (for licensing consideration) the nature of specs the group is permitted to create, without having to commit to creating particular specs.  That's especially useful for groups like this, where the group needs to figure some things out, including what it wants to work on (after the group exists to figure that out).

**Comment by swickr** [comment]
Thanks @wcarr; #46 mostly works for me.  I've made some final comments there.

**Comment by rigow** [comment]
Merged the agreed wording into gh-pages
