### ISSUE TITLE
[hasec charter] Unusual disenfranchisement of Invited Experts

### ISSUE THREAD

**Issue by swickr** [w3c/websec#43]
Section 7. Decision Policy states that consensus is determined without the inclusion of any Invited Experts.  Why are Invited Experts disenfranchised this way in this group?

I suggest using the conventional text "...consensus among the Working Group participants ..."

**Comment by rigow** [comment]
This text came from the template used. You may want to address that with Doug who's at the origin of the template. I will address this with another PR

**Comment by rigow** [comment]
resolved with PR #52
