### ISSUE TITLE
[hasec charter] put new storage mechanisms out of scope

### ISSUE THREAD

**Issue by swickr** [w3c/websec#44]
2.1 Restricted Scope, item Secure Hardware Storage API, has the sentence

>  It is expected the specification would reference existing Web platform storage specifications, not define new storage APIs.

This is too weak.  The Hardware Security WG should not define new storage mechanisms.  This WG should (if it chooses to work on this Restricted Scope item) propose secure enhancements to the existing Web Platform storage APIs.

Recommended rephrasing:

> This API must enhance (an) existing Web Platform storage API(s), not create a new storage mechanism.

**Comment by wayneca** [comment]
@swickr  I created a PR for the suggested wording. #48  Sounds good to me.

**Comment by rigow** [comment]
merged agreed text into gh-pages
