### ISSUE TITLE
[hasec charter] flexible copyright for some specs

### ISSUE THREAD

**Issue by wayneca** [w3c/websec#59]
W3C has two copyright licenses.  One of them allows flexibly shifting work back and forth with a Community Group.  That's particularly useful for specs without input incubator specs where related work may be done in a CG.  It also allows continued use and modification of specs if they bog down due to lack of Browser implementation.  This proposal would only apply to the Secure Worker Restricted Scope Item and the related Secure Hardware Storage and Secure IO restricted cope items (and the discovery/authentication related to using those services).  Without this there is a risk that contributors of input specs who use those specs in their own projects could get stuck with the spec stalled, but not abandoned (e.g. due to lack of implementer interest other than from the contributor).  An alternative to using the more permissive license is to do the work in a CG, passing it into the WG for publication.  The more permissive copyright license makes makes that unnecessary since copyright licenses in both CG and WG would be compatible. Suggested wording at #58

**Comment by vgalindo** [comment]
@wcarr question on my side : why would you apply the flexible scheme only to few items and not others ?

**Comment by vgalindo** [comment]
@rigo can u allocate that issue to #hasec label ? thxs

**Comment by wayneca** [comment]
> @wcarr question on my side : why would you apply the flexible scheme only to few items and not others ?

@vgalindo I'd prefer it to be applied to all the deliverables from the WG.  But, if there are objections to using it for some of the deliverables, it should be applied to at least those restricted scope items I listed.

That text is based on the [W3C Web Platform WG Charter](https://www.w3.org/2015/10/webplatform-charter.html#licensing).  It's also in the [proposed W3C Device and Sensor WG Charter](https://www.w3.org/2015/11/DeviceSensorsCharter.html#patentpolicy) (the new name for the DAP WG).  I'd prefer the wording in those, so not limiting it to just some of the deliverables.

**Comment by wayneca** [comment]
#58 and #60 are two alternatives for wording for this issue.  #60 addresses @vgalindo comment

**Comment by vgalindo** [comment]
@wcarr  We need to proceed with the AC review, and we lack time to ask all current supporters their view on the licensing aspects. I suggest that we proceed with the member review and that you bring this at that point.

**Comment by rigow** [comment]
A community group offers less assurances for development than a WG. So why would we shift stuff between some not yet existant CG and the WG? Note that taking on work that has been developed in a CG and where the CG participants have signed the final CG agreement is a well designed process within W3C. The Web Platform WG or former HTML(5) WG had very special challenges from some of its participants. I don't see a need for such a complex setup here just in case a person could come up with a remark. Note that copyright is not the issue when shifting work between CG and WG. Patent rights are. So the proposed change in license does not benefit anybody and adds complexity and questions as people will ask why their work is fully forkable by their competitors. At least that was a regular discussion the HTML WG had. You can always take your own work anywhere, so there is no lock-in situation.

**Comment by wayneca** [comment]
@rigow You can always take your own work elsewhere, but you can't necessarily take improvements made by the group that transforms that work.

It isn't just the HTML WG using the more permissive W3C license.  It is used by the proposed Device and Sensor WG and the Web Payments WG and most recent charters.  

The proposed specs in this group typically do not have incubator specs.   That is increasingly seen as an issue, that IGs or CGs are better for exploration than a WG and that WGs should work where it is clearer what the direction of the spec should be.  The more permissive license removes at least one impediment to working on immature drafts in a WG and ease sharing that early work with a CG (especially for parts that turn out to need multiple versions for experimentation).
