### ISSUE TITLE
[hasec charter] conducts tech work on mailing list?  or GitHub too

### ISSUE THREAD

**Issue by wayneca** [w3c/websec#64]
from [proposed hasec charter](https://w3c.github.io/websec/hasec-charter#communication):

> This group primarily conducts its technical work on the public mailing list at public-hasec-wg@w3.org (archive).

Is that intended or will technical discussions occur on GitHub as is becoming common in WGs?  e.g. see recent [Web Authentication WG Charter](https://www.w3.org/2015/12/web-authentication-charter.html#communication).

> This group primarily conducts its technical work through a GitHub repository and on the public mailing list public-webauthn@w3.org (archive). The public is invited to raise issues on GitHub.

**Comment by rigow** [comment]
Wayne, do you believe we should determine whether we should use google searches while working on HASEC? Or intel chips? I think you're going into too much detail. The boilerplate text is over 10 years old and is mainly there to indicate that the group is working in public.

**Comment by vgalindo** [comment]
@wcarr @rigow The use up to now is to let the Working Group choosing its way of working - even if I will be suggesting that we favor github usage, we have to make sure everyone agrees and can access github. So lets address that once the group is created...

**Comment by wayneca** [comment]
@rigow @vgalindo

The boilerplate being used says "This group primarily conducts its technical work on the public mailing list at public-hasec-wg@w3.org (archive)."  

Recent WG charters (pointer events, web authentication) that don't say anything about GitHub use the sentence: "Technical discussions for this Working Group are conducted in [public](https://www.w3.org/2015/Process-20150901/#confidentiality-levels)."   They don't say that technical discussions are expected to be on the mail list when they mean are public.  By my count, 2 of the last 6 used the old template language (and they may have meant it).
