### ISSUE TITLE
[hasec charter]add Web Authentication WG to charter, no overlap

### ISSUE THREAD

**Issue by wayneca** [w3c/websec#66]
The Web Authentication WG should be added to the hasec wg charter in the [internal liaisons section](https://w3c.github.io/websec/hasec-charter#coordination).  In the [Out of Scope section](https://w3c.github.io/websec/hasec-charter#scope), add that the hasec WG will not overlap the scope of the Web Authentication WG, that it will not define competing ways to authenticate the user to the Web Server that delivered the Web page.

**Comment by vgalindo** [comment]
the charter has been finalized.
