### ISSUE TITLE
[hasec charter] Note that Secure Element API from SysApps is out of scope

### ISSUE THREAD

**Issue by wayneca** [w3c/websec#68]
In the [Out of Scope section](https://w3c.github.io/websec/hasec-charter#scope), add that the Secure Element API as in the [SysApps WG](https://www.w3.org/2012/sysapps/) is not in scope under this Charters Restricted Scope Items, and that the WG would have to recharter to work on a spec like that.

**Comment by vgalindo** [comment]
the charter has been finalized.
