### ISSUE TITLE
[hasec charter] remove Binding mechanism restricted scope item

### ISSUE THREAD

**Issue by wayneca** [w3c/websec#69]
To avoid confusion of overlap with the Web Payments WG, remove the Binding mechanism restricted scope item.  #65 shows hasec can be used for Web Payments without adding that item.

In Web payments, an invoice could be a json object that is digitally signed by the merchant.  That could be passed to the Payment app by the Browser, and the Payment app could return the previously digitally signed invoice inside a digitally signed payment confirmation.  The Web Payments WG would define that, not the hasec WG.  It's doesn't look like the hasec spec would need to add any new API to allow the Web Payments WG to do that.

Removing unneeded restricted scope items could ease concerns about the hasec WG charter being too broad where it isen't clear what the use cases are and where there isn't an incubator spec.

**Comment by vgalindo** [comment]
the charter has been finalized.
