### ISSUE TITLE
Include changes from Virignie 23 Nov docx

### ISSUE THREAD

**Issue by rigow** [w3c/websec#7]
Virginie sent around a document 23 Nov with change control. Those changes have to be integrated into the charter

**Comment by vgalindo** [comment]
Thanks rigo !

**Comment by wayneca** [comment]
Where is the 23 November doc?  Sent where?

**Comment by rigow** [comment]
@vgalindo can you check the current charter? I think most of the document from 23 Nov has been merged into the charter and has already moved from there. If not, please tell and I will create a pull request

**Comment by cyberphone** [comment]
The end-date is extremely optimistic given the fact that there are no input documents.  Three years seem like a more plausible time-line.

**Comment by vgalindo** [comment]
@wcarr that doc was sent ot the team only, a long time ago. 
@rigow  Changes have been integrated
@cyberphone the WG need to gather and contributions are expected. 
--> I suggest we close that issue

**Comment by rigow** [comment]
Ok and done
