### ISSUE TITLE
[hasec charter] add a section on incubation drafts in CG

### ISSUE THREAD

**Issue by wayneca** [w3c/websec#70]
Add a section that says FPWD's will not be published until there are incubator drafts with general acceptance in the hasec WG and some indicator of implementer participation and interest in implementing the drafts.  This incubator work could be done in one or more CGs.  This addresses concerns that have been raised in the past that publishing FPWDs when a WG is exploring possible directions can cause confusion about W3C's direction.  It is easier in a CG to develop multiple different approaches in areas where it isn't clear yet what a single approach is.  An example of this is the development of Web Payment approaches in CGs for the Web Payments WG.

**Comment by vgalindo** [comment]
The charter has been finalized.
