### ISSUE TITLE
3.1 National electronic identity for accessing public services

### ISSUE THREAD

**Issue by mark-orz** [w3c/websec#93]
"As of today, a large number of european countries have deployed electronic identity, and do offer their citizen the access to to governement services such as paying tax, managing pensions."
Change to
"As of 2016, a large number of European countries have already deployed electronic identity systems and offer their citizens access to government services such as paying tax or managing pensions."

"Eaxmples of countries and associated systems are : Estonia with eEstonia, Belgium eID with eService ecosystem, Sweden with a Tax Agency card and Telia eID, Norway with its ID-porten"
Change to
"Examples of countries and associated systems are:
- Estonia: eEstonia
- Belgium: eID with eService ecosystem
- Sweden: Tax Agency card and Telia eID
- Norway: ID-porten
- United Kingdom: GOV.UK Verify"
  Note: not clear whether this paragraph means to refer specifically to hardware based solutions, or to software based solutions (such as GOV.UK Verify).

"Whatever is the service accessed, it is expected by the citizen that he or she owns a hardware based token, that will carry its electronic identity."
Change to
"Whatever the service accessed, the citizen will be expected to own a hardware token that will carry their electronic identity."

"The native environment, installed on the citizen device, or on the public service office is able to access to the hardware token, thanks to a physical link (USB, ISO, BLE, ...). "
(I don't quite understand this sentence, perhaps change to)
"The native environment of the citizen's devices can access the hardware token through a physical link using a transport mechanism such as USB, ISO, BLE or NFC".
(Really ISO? I'm only familiar with the disk image file format which doesn't seem right here.)

**Comment by sbahloul** [comment]
> Note: not clear whether this paragraph means to refer specifically to hardware based solutions, or to software based solutions (such as GOV.UK Verify).

This section is oriented to hardware based solutions.

**Comment by sbahloul** [comment]
> Really ISO? I'm only familiar with the disk image file format which doesn't seem right here.

The mention here is about ISO/IEC 7816 (https://en.wikipedia.org/wiki/ISO/IEC_7816) => I fix it
