### ISSUE TITLE
3.3 Transparent device authentication for online payment confirmation on 3DSecure scheme

### ISSUE THREAD

**Issue by mark-orz** [w3c/websec#96]
Opening an issue because this section is still to be written.

**Comment by sbahloul** [comment]
Virginie: did you get the contact details of Brian@VISA ?

**Comment by cyberphone** [comment]
3D Secure is a "workaround" which more recent schemes like Apple Pay doesn't need.

**Comment by vgalindo** [comment]
As of today, no news from Visa, I guess we should remove that section.
